#!/bin/bash

# Before running this script, make sure you have sysbench installed:
#           sudo apt-get install sysbench
#
# This script helps you check if your Raspberry pi is correctly powered.
# You can read more about Raspberry pi powering issues here: https://ownyourbits.com/2019/02/02/whats-wrong-with-the-raspberry-pi/

# Helper function to decode throttled code
function throttleCodeMask {
    perl -e "printf \"%s\", $1 & $2 ? \"$3\" : \"$4\""
}

# Make the throttled code readable
#
# See the `get_throttled` method documentation on: https://www.raspberrypi.org/documentation/raspbian/applications/vcgencmd.md
#

function throttledToText {
    throttledCode=$1
    throttleCodeMask "${throttledCode}" 0x80000 "Soft temperature limit has occurred, "
    throttleCodeMask "${throttledCode}" 0x40000 "Throttling has occurred, "
    throttleCodeMask "${throttledCode}" 0x20000 "Arm frequency capping has occurred, "
    throttleCodeMask "${throttledCode}" 0x10000 "Under-voltage has occurred, "
    throttleCodeMask "${throttledCode}" 0x8 "Soft temperature limit active, "
    throttleCodeMask "${throttledCode}" 0x4 "Currently throttled, "
    throttleCodeMask "${throttledCode}" 0x2 "Arm frequency capped, "
    throttleCodeMask "${throttledCode}" 0x1 "Under-voltage detected, "
}

# Main script, kill sysbench when interrupted
trap 'kill -HUP 0' EXIT
# errors to /dev/null
sysbench --test=cpu --cpu-max-prime=10000000 --num-threads=3 run &>/dev/null &
maxfreq=$(( "$(awk '{printf ("%0.0f",$1/1000); }' < /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq)" -15 ))

# Read sys info, print and loop
printf "\033[s"
while true; do
    printf "\033[u\033[0J"
    date
    temp="$(vcgencmd measure_temp | cut -f2 -d=)"
    CPUUTIL="$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{printf ("%0.0f",100 - $1); }')"
    # % memory used
    MEMUSED="$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')"
    real_clock_speed="$(vcgencmd measure_clock arm | awk -F"=" '{printf ("%0.0f", $2 / 1000000); }' )"
    sys_clock_speed="$(awk '{printf ("%0.0f",$1/1000); }' </sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)"
    voltage="$(vcgencmd measure_volts | cut -f2 -d= | sed 's/000//')"
    throttled_text="$(throttledToText "$(vcgencmd get_throttled | cut -f2 -d=)")"
    echo "Temp:    $temp"
    echo "Clock:   $sys_clock_speed / $real_clock_speed MHz"
    echo "CPU load: $CPUUTIL % (max freq: $maxfreq MHz) "
    echo "Memory used: $MEMUSED %"
    echo "Voltage: $voltage - $throttled_text"
    # check benchmark process is running, if not, exit
    pgrep "bench" > /dev/null || exit 0
    echo "Benchmark still running..."
    sleep 5

done
